//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSpecifications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarSpecifications()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int Specification_id { get; set; }
        public string CarBody { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public string Transmission { get; set; }
        public Nullable<double> EngineVolume { get; set; }
        public Nullable<double> EnginePower { get; set; }
        public Nullable<double> MaxSpeed { get; set; }
        public Nullable<double> FuelConsumption { get; set; }
        public string CarColor { get; set; }
        public string CarPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
    }
}
