//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Car_id { get; set; }
        public Nullable<int> Admin_id { get; set; }
        public Nullable<int> Brand_id { get; set; }
        public Nullable<int> Model_id { get; set; }
        public Nullable<int> Specification_id { get; set; }
        public Nullable<int> Location_id { get; set; }
        public Nullable<double> RentalPrice { get; set; }
        public string CarStatus { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual CarBrands CarBrands { get; set; }
        public virtual CarLocations CarLocations { get; set; }
        public virtual CarModels CarModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual CarSpecifications CarSpecifications { get; set; }
    }
}
