//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Order_id { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public Nullable<int> Car_id { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Сustomers Сustomers { get; set; }
    }
}
